# Generated by Django 6.0 on 2025-12-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='category_name',
            new_name='category',
        ),
    ]
